add random string to resources prefix
VolumezTech/volumez pull request #44
Opened 2024-06-20 14:05 UTC by VolumezTech

2024-06-23 11:31 UTC, nkorobko requested changes
How will look the final name with this code?

2024-06-23 11:31 UTC, nkorobko commented on terraform/aws/examples/ec2/complete/easy_starter/easy_starter.tfvars
> +resources_name_prefix = "iginor"
Change it to "volumez" plz

2024-06-23 14:19 UTC, itaygvlz commented
<resource-prefix>-<random-string>-<resource-type>

2024-06-24 10:18 UTC, nkorobko approved these changes

2024-06-24 10:20 UTC, merged